# Generated by Django 5.1.5 on 2025-01-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
